language: java
sudo: false

jdk:
  - oraclejdk8

notifications:
  email: false

branches:
  only:
    - master

after_success:
  - mvn clean test jacoco:report coveralls:report
  - bin/ci-push-javadoc.sh
  - bin/ci-deploy-snapshot.sh